version: '3.8'

services:
  indexer:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/indexer
      - FOSSIL_DB_URL=postgresql://user:pass@fossil-db:5432/fossil
      - MAINNET_RPC_URL=${MAINNET_RPC_URL}